GET http://localhost:8102/game
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjo0LCJzdGVhbUlkIjo3NjU2MTE5ODM5MzUwNDQ2MCwicHJpbWFyeUxvY2F0aW9uIjp7ImlkIjoxfSwiZGlzcGxheU5hbWUiOiJGb3h4IiwibGV2ZWwiOjEsImNyZWRpdHMiOjAsInhwIjowfSwiaWF0IjoxNzIwODc3NjMwLCJleHAiOjIwMzY0NTM2MzB9.Xf0dJLWUhUtJvvvMc6h6JYke7N5G0_js_Yc4LoUlHMo
